language: python
python:
  - "2.6"
  - "2.7"

# Use new Travis infrastructure (Docker can't sudo yet)
sudo: false

# Install coveralls to obtain code coverage
install:
  - "pip install coveralls"
  - "pip install flake8"

before_install:
  # Need this for the git tests to succeed.
  - git config --global user.email "spack@example.com"
  - git config --global user.name "Test User"
  # Need this to be able to compute the list of changed files
  - git fetch origin develop:develop

script:
  - . share/spack/setup-env.sh
  - spack compilers
  - spack config get compilers
  - spack install -v libdwarf
  # Run unit tests with code coverage
  - coverage run bin/spack test
  # Checks if the file that have been changed are flake8 conformant
  - CHANGED_PYTHON_FILES=`git diff develop... --name-only | perl -ne 'print if /\.py$/'`
  - if [[ ${CHANGED_PYTHON_FILES} ]] ; then flake8 --format pylint --config flake8.ini ${CHANGED_PYTHON_FILES} ; fi


after_success:
  - coveralls

notifications:
  email:
    recipients:
      - tgamblin@llnl.gov
    on_success: change
    on_failure: always
