language: python

python:
  - "2.6"
  - "2.7"
env:
  - TEST_TYPE=unit
  - TEST_TYPE=flake8

# Exclude flake8 from python 2.6
matrix:
  exclude:
  - python: "2.6"
    env: TEST_TYPE=flake8

# Use new Travis infrastructure (Docker can't sudo yet)
sudo: false

# Install coveralls to obtain code coverage
install:
  - "pip install coveralls"
  - "pip install flake8"

before_install:
  # Need this for the git tests to succeed.
  - git config --global user.email "spack@example.com"
  - git config --global user.name "Test User"

  # Need this to be able to compute the list of changed files
  - git fetch origin develop:develop

script:
  # Run unit tests with code coverage plus install libdwarf
  - 'if [ "$TEST_TYPE" = "unit" ]; then share/spack/qa/run-unit-tests; fi'
  # Run flake8 code style checks.
  - 'if [ "$TEST_TYPE" = "flake8" ]; then share/spack/qa/run-flake8; fi'

after_success:
  - 'if [ "$TEST_TYPE" = "unit" ] && [ "$TRAVIS_PYTHON_VERSION" = "2.7" ]; then coveralls; fi'

notifications:
  email:
    recipients:
      - tgamblin@llnl.gov
    on_success: change
    on_failure: always
